#!/usr/bin/env python3
"""
NODIUM — BUILD TOOL
--------------------
Reads the editable content in data/ (site.json, categories.json, products.json)
and generates:

  1. assets/js/data.js          — the single runtime data bundle (window.NODIUM)
  2. one category page per category (e.g. notion-templates.html)
  3. sitemap.xml

Run after ANY edit to data/ files:
    python3 tools/build.py

No other build step is required — the site is plain HTML/CSS/JS and can be
deployed as-is (Netlify, Vercel, GitHub Pages, any static host).
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
IMG = os.path.join(ROOT, "assets", "images", "cat")

def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return json.load(f)

def img_path(key):
    """Resolve an image key (e.g. 'notion-1') to its real file path (jpg or svg)."""
    for ext in (".jpg", ".png", ".svg"):
        p = os.path.join(IMG, key + ext)
        if os.path.exists(p):
            return f"assets/images/cat/{key}{ext}"
    raise SystemExit(f"Missing image for key: {key}")

# ------------------------------------------------------------------ load sources
site = load("site.json")
categories = load("categories.json")["categories"]
products = load("products.json")["products"]

cfg = site["config"]
site_url = cfg["siteUrl"].rstrip("/")

# ------------------------------------------------------------------ resolve images
img_map = {}
for c in categories:
    for k in (c.get("cover"), c.get("cover2")):
        img_map[k] = img_path(k)
for p in products:
    for k in ([p.get("cover")] + p.get("gallery", [])):
        if k:
            img_map[k] = img_path(k)

# quick integrity checks
slugs = {c["slug"] for c in categories}
for p in products:
    if p["category"] not in slugs:
        raise SystemExit(f"Product '{p['slug']}' has unknown category '{p['category']}'")
    if len({p["slug"] for p in products}) != len(products):
        raise SystemExit("Duplicate product slugs found")

# ------------------------------------------------------------------ data.js bundle
bundle = {
    "config": cfg,
    "home": site.get("home"),
    "about": site.get("about"),
    "faqs": site.get("faqs"),
    "contact": site.get("contact"),
    "checkout": site.get("checkout"),
    "order": site.get("order"),
    "categories": categories,
    "products": products,
    "img": img_map,
}

js = (
    "/* ============================================================\n"
    "   NODIUM — runtime site data (AUTO-GENERATED)\n"
    "   Do NOT edit this file directly.\n"
    "   Edit data/site.json, data/categories.json or data/products.json,\n"
    "   then run:  python3 tools/build.py\n"
    "   ============================================================ */\n"
    "window.NODIUM = " + json.dumps(bundle, ensure_ascii=False, indent=2) + ";\n"
)
with open(os.path.join(ROOT, "assets", "js", "data.js"), "w", encoding="utf-8") as f:
    f.write(js)
print("wrote assets/js/data.js")

# ------------------------------------------------------------------ category pages
def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))

def page_template(c):
    title = f"{c['name']} — {cfg['siteName']}"
    desc = c["short"]
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <!-- ============ NODIUM category page (generated by tools/build.py) ============ -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{esc(title)}</title>
  <meta name="description" content="{esc(desc)}">
  <link rel="canonical" href="{site_url}/{c['slug']}.html">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="{esc(cfg['siteName'])}">
  <meta property="og:title" content="{esc(title)}">
  <meta property="og:description" content="{esc(desc)}">
  <meta property="og:url" content="{site_url}/{c['slug']}.html">
  <meta property="og:image" content="{site_url}/{img_map[c['cover']]}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="theme-color" content="#0A0A0A">
  <link rel="icon" type="image/svg+xml" href="favicon.svg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/main.css?v=1">
  <script type="application/ld+json">
  {{"@context":"https://schema.org","@type":"CollectionPage","name":"{esc(c['name'])}","description":"{esc(desc)}","url":"{site_url}/{c['slug']}.html","isPartOf":{{"@type":"WebSite","name":"{esc(cfg['siteName'])}","url":"{site_url}"}}}}
  </script>
</head>
<body data-page="category" data-category="{c['slug']}">
  <a class="skip-link" href="#main">Skip to content</a>
  <div id="app-header"></div>
  <main id="main">
    <!-- category hero + product grid are rendered from data by assets/js/category.js -->
    <div id="category-root" class="page-shell"></div>
  </main>
  <div id="app-footer"></div>
  <div id="cart-drawer"></div>
  <div id="toast" role="status" aria-live="polite" class="toast" hidden></div>
  <script src="assets/js/data.js?v=1"></script>
  <script src="assets/js/app.js?v=1"></script>
  <script src="assets/js/cart.js?v=1"></script>
  <script src="assets/js/category.js?v=1"></script>
</body>
</html>
"""

for c in categories:
    with open(os.path.join(ROOT, c["slug"] + ".html"), "w", encoding="utf-8") as f:
        f.write(page_template(c))
    print("wrote", c["slug"] + ".html")



# ------------------------------------------------------------------ sitemap.xml
pages = ["index.html", "products.html", "about.html", "faq.html", "contact.html",
         "checkout.html", "order-confirmation.html", "terms.html", "privacy.html",
         "refund-policy.html", "404.html"] + [c["slug"] + ".html" for c in categories]
urls = [f"<url><loc>{site_url}/{p}</loc></url>" for p in pages if p != "404.html"]
urls += [f"<url><loc>{site_url}/product.html?slug={p['slug']}</loc></url>" for p in products]

sitemap = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + "\n".join(urls) + "\n</urlset>\n"
)
with open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8") as f:
    f.write(sitemap)
print("wrote sitemap.xml")

print(f"\nDone. {len(categories)} categories, {len(products)} products, {len(img_map)} images.")
